### ISSUE TITLE
SelectedVideoInputId is null

### ISSUE THREAD

**Issue by Hackmodford** [sabitertan/BlazorBarcodeScanner#13] opened 2021-05-17 14:55 UTC
For some reason the SelectedVideoInputId is null.

```
private void DecodingChanged(DecodingChangedArgs args)
{
    var test = _barcodeReader.SelectedVideoInputId;
    // test is null and I don't know why :/
}
```

**Comment by uniederer** [comment] 2021-05-19 09:19
What's the status of IsDecoding when you encounter that issue? - `SelectedVideoInputId` is set prior changing IsDecoding to `true`. Yet it's not set at all if `IsDecoding` is going false.

What I could imagine is though, that I created a race due to async execution of the start command. Did you check the console output? Is it possible, that you receive the `DecodingChanged`-Event before you see `Started continous decode from camera with id ...` in the console?

**Comment by sabitertan** [comment] 2021-05-27 10:09
I can't reproduce this issue, @Hackmodford  can you provide an example?

**Comment by sabitertan** [comment] 2021-06-21 20:11
Long time no input, closing.

**Closed by sabitertan** 2021-06-21 20:11 UTC
